unbind r
bind r source-file ~/.tmux.conf

set -g history-limit 10000000

set -g mouse on

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind C-k clear-history

set-option -gw mode-keys vi
set-option -s copy-command 'pbcopy'
bind-key -T copy-mode-vi v { send-keys -X begin-selection }
bind-key -T copy-mode-vi C-v { send-keys -X rectangle-toggle }
bind-key -T copy-mode-vi V { send-keys -X select-line }

set-option -g status-position top
set -g status-style "bg=default,fg=#787c99"
set -g status-left "#[fg=#7aa2f7,bold] ■ #S  "
set -g status-left-length 20
set -g status-right ""
setw -g window-status-format "#[fg=#565f89] #I:#W "
setw -g window-status-current-format "#[fg=#7aa2f7,bold,underline] #I:#W "
set -g status-justify left
