unbind r
bind r source-file ~/.tmux.conf

set -g history-limit 10000000

set -g mouse on

bind | split-window -h
bind - split-window -v

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind C-k clear-history

set-option -gw mode-keys vi
set-option -s copy-command 'pbcopy'
bind-key -T copy-mode-vi v { send-keys -X begin-selection }
bind-key -T copy-mode-vi C-v { send-keys -X rectangle-toggle }
bind-key -T copy-mode-vi V { send-keys -X select-line }
